export const ITEMS_TASKS = [
    {
        Description: 'Построить дерево',
        state: 'В процессе',
        LastDateUpdate: '19.09.19',
    },
    {
        Description: 'Вырастить дом',
        state: 'В процессе',
        LastDateUpdate: '19.09.19',
    },
    {
        Description: 'Посадить сына',
        state: 'В процессе',
        LastDateUpdate: '19.09.19',
    },
];

export const ITEMS_AGREEMENTS = [
    {
        DocumentId: 1,
        DocumentType: 0,
        ProjectId: 2,
        Status: 0,
        Result: 0,
        DateCreate: '2019-10-15T21:03:11.201917+03:00',
        DateEnd: '2019-10-15T21:03:11.2029196+03:00',
        LastDateUpdate: '2019-10-15T21:03:11.2029196+03:00',
        PerformanceList: [
            {
                ParticipantId: 1,
                ProjectUserRole: {
                    EmployeeId: 1,
                    Employee: {
                        Name: 'sample string 1',
                        Email: 'sample string 2',
                        Phone: 'sample string 3',
                        Position: 'sample string 4',
                        OrganizationId: 1,
                        Organization: {
                            Name: 'sample string 1',
                            ShortName: 'sample string 2',
                            IKO: 'sample string 3',
                            INN: 'sample string 4',
                            AddressLegal: 'sample string 5',
                            AddressMail: 'sample string 6',
                            Phone: 'sample string 7',
                            Fax: 'sample string 8',
                            Email: 'sample string 9',
                            Id: 10,
                        },
                        IsCustomer: true,
                        UserId: 1,
                        User: {
                            Login: 'sample string 1',
                            HashPassword: 'sample string 2',
                            UserName: 'sample string 3',
                            Email: 'sample string 4',
                            UserId: 'sample string 5',
                            Id: 6,
                        },
                        RefUrlAvatar: 'sample string 6',
                        Id: 7,
                    },
                    ProjectRole: 0,
                    ProjectId: 2,
                    Id: 3,
                },
                AgreementId: 1,
                Result: 0,
                Date: '2019-10-15T21:03:11.205929+03:00',
                Comment: 'sample string 3',
                Id: 4,
            },
            {
                ParticipantId: 1,
                ProjectUserRole: {
                    EmployeeId: 1,
                    Employee: {
                        Name: 'sample string 1',
                        Email: 'sample string 2',
                        Phone: 'sample string 3',
                        Position: 'sample string 4',
                        OrganizationId: 1,
                        Organization: {
                            Name: 'sample string 1',
                            ShortName: 'sample string 2',
                            IKO: 'sample string 3',
                            INN: 'sample string 4',
                            AddressLegal: 'sample string 5',
                            AddressMail: 'sample string 6',
                            Phone: 'sample string 7',
                            Fax: 'sample string 8',
                            Email: 'sample string 9',
                            Id: 10,
                        },
                        IsCustomer: true,
                        UserId: 1,
                        User: {
                            Login: 'sample string 1',
                            HashPassword: 'sample string 2',
                            UserName: 'sample string 3',
                            Email: 'sample string 4',
                            UserId: 'sample string 5',
                            Id: 6,
                        },
                        RefUrlAvatar: 'sample string 6',
                        Id: 7,
                    },
                    ProjectRole: 0,
                    ProjectId: 2,
                    Id: 3,
                },
                AgreementId: 1,
                Result: 0,
                Date: '2019-10-15T21:03:11.205929+03:00',
                Comment: 'sample string 3',
                Id: 4,
            },
        ],
        Id: 6,
    },
];
